### ISSUE TITLE
autocomplete fails to load.

### ISSUE THREAD

**Issue by sandikata** [h-hirokawa/atom-autocomplete-ansible#51] opened 2020-10-09 06:36 UTC
TypeError: find_plugins() missing 1 required positional argument: 'ptype'

ArchLinux

**Comment by dnorthup-ums** [comment] 2020-10-09 14:25
@sandikata This looks like a duplicate of #50. Can you please tell me what versions of Python, Atom, and Ansible you are using, and if you are using a Python venv?

**Comment by sandikata** [comment] 2020-10-12 08:48
Python 3.8 (Ubuntu 20.04) Latest Atom and ansible 2.9

**Comment by dnorthup-ums** [comment] 2020-10-13 13:42
Ok, TY.

**Comment by dnorthup-ums** [comment] 2020-10-13 13:54
@sandikata Work for this will continue on #50 .

**Closed as completed by dnorthup-ums** 2020-10-13 13:54 UTC
Labels: duplicate

**Comment by dnorthup-ums** [comment] 2020-11-25 19:12
Fixed with #56
